-- Script SQL para insertar Perfumes de Mujer en Supabase (Precios en Pesos Argentinos ARS)

INSERT INTO perfumes (
  id, name, brand, category, gender, price, original_price, ml_options, image, description,
  top_notes, heart_notes, base_notes, accords, longevity, projection, is_bestseller, is_new, stock, rating, reviews_count
) VALUES 
(
  'lattafa-yara-pink',
  'Yara Pink Eau de Parfum',
  'Lattafa Perfumes',
  'arabe',
  'mujer',
  55000.00,
  68000.00,
  ARRAY[100],
  '/images/amber_vanilla.png',
  'Una fragancia femenina irresistiblemente dulce y cremosa. Yara combina orquídeas tropicales, helado de fresa, coco cremoso y una base atalcada de vainilla gourmand y almizcle. Un éxito viral de la perfumería árabe.',
  ARRAY['Orquídea', 'Heliotropo', 'Tangerina'],
  ARRAY['Acorde Gourmand', 'Frutas Tropicales', 'Coco'],
  ARRAY['Vainilla', 'Almizcle', 'Sándalo'],
  ARRAY['Dulce', 'Cremoso', 'Frutal', 'Vainilla', 'Atalcado'],
  '9-11 Horas',
  'Fuerte',
  true,
  true,
  25,
  4.9,
  180
),
(
  'armaf-club-de-nuit-woman',
  'Club De Nuit Woman',
  'Armaf Dubai',
  'arabe',
  'mujer',
  58000.00,
  72000.00,
  ARRAY[105],
  '/images/amber_vanilla.png',
  'La expresión definitiva del lujo femenino oriental. Inspirado en Coco Mademoiselle, abre con notas cítricas vibrantes de naranja y bergamota, evolucionando hacia un corazón de rosa y jazmín con fondo de pachulí y vainilla sensual.',
  ARRAY['Naranja', 'Bergamota', 'Toronja', 'Durazno'],
  ARRAY['Rosa', 'Jazmín', 'Lichi', 'Geranio'],
  ARRAY['Pachulí', 'Vainilla', 'Almizcle', 'Vértiver'],
  ARRAY['Cítrico Elegante', 'Floral', 'Pachulí', 'Dulce', 'Fresco'],
  '10+ Horas',
  'Muy Fuerte',
  true,
  false,
  19,
  4.8,
  155
),
(
  'ch-good-girl',
  'Good Girl Eau de Parfum',
  'Carolina Herrera',
  'disenador',
  'mujer',
  165000.00,
  185000.00,
  ARRAY[50, 80],
  '/images/designer_black.png',
  'Una fragancia audaz y sofisticada. Good Girl combina la luz del jazmín y el nardo con la oscuridad del cacao y la haba tonka. Representa la dualidad de la mujer moderna.',
  ARRAY['Almendra', 'Café', 'Bergamota', 'Limón'],
  ARRAY['Jazmín Sambac', 'Nardo', 'Lirio', 'Flor de Azahar'],
  ARRAY['Haba Tonka', 'Cacao', 'Vainilla', 'Pachulí', 'Sándalo', 'Ámbar'],
  ARRAY['Dulce', 'Aromático', 'Cacao', 'Blanco Floral', 'Cálido'],
  '10-12 Horas',
  'Fuerte',
  true,
  false,
  12,
  4.9,
  240
),
(
  'ysl-libre-edp',
  'Libre Eau de Parfum',
  'Yves Saint Laurent',
  'disenador',
  'mujer',
  175000.00,
  195000.00,
  ARRAY[50, 90],
  '/images/amber_vanilla.png',
  'El perfume de la libertad audaz. Combina la esencia de lavanda de Francia con la sensualidad de la flor de azahar de Marruecos y una nota audaz de orquídea salvaje y vainilla.',
  ARRAY['Lavanda', 'Mandarina', 'Grosella Negra', 'Petigrain'],
  ARRAY['Flor de Azahar del Naranjo', 'Jazmín'],
  ARRAY['Vainilla de Madagascar', 'Almizcle', 'Ámbar Gris', 'Cedro'],
  ARRAY['Floral', 'Lavanda', 'Cítrico', 'Vainilla', 'Atalcado'],
  '11+ Horas',
  'Fuerte',
  true,
  true,
  14,
  4.9,
  195
),
(
  'dior-jadore',
  'J''adore Eau de Parfum',
  'Dior Paris',
  'disenador',
  'mujer',
  180000.00,
  205000.00,
  ARRAY[50, 100],
  '/images/royal_blue.png',
  'Un ramo floral extraordinario y voluptuoso. J''adore une la esencia de Ylang-Ylang con notas afrutadas de Rosa Damascena y Jazmín de Grasse para crear un perfume de oro líquido puro.',
  ARRAY['Melón', 'Durazno', 'Pera', 'Bergamota', 'Mandarina'],
  ARRAY['Jazmín', 'Lirio de los Valles', 'Rosa', 'Orquídea', 'Violeta'],
  ARRAY['Almizcle', 'Vainilla', 'Zarzamora', 'Cedro'],
  ARRAY['Floral Blanco', 'Frutal', 'Dulce', 'Fresco', 'Ozónico'],
  '9-11 Horas',
  'Moderada a Fuerte',
  false,
  false,
  8,
  4.8,
  210
)
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price;
