-- Script SQL para insertar el catálogo inicial de perfumes en Supabase (Precios en Pesos Argentinos ARS)

INSERT INTO perfumes (
  id, name, brand, category, gender, price, original_price, ml_options, image, description,
  top_notes, heart_notes, base_notes, accords, longevity, projection, is_bestseller, is_new, stock, rating, reviews_count
) VALUES 
(
  'lattafa-khamrah',
  'Khamrah Eau de Parfum',
  'Lattafa Perfumes',
  'arabe',
  'unisex',
  68000.00,
  85000.00,
  ARRAY[100],
  '/images/amber_vanilla.png',
  'Una obra maestra oriental dulcemente especiada. Khamrah combina canela aromática, nuez moscada y praliné cremoso sobre una cálida base de canela, ámbar dulce y madera de agar (Oud). Perfecto para eventos nocturnos y clima frío.',
  ARRAY['Canela', 'Nuez Moscada', 'Bergamota'],
  ARRAY['Praliné', 'Dátiles', 'Tuberosa', 'Mahonial'],
  ARRAY['Vainilla de Madagascar', 'Habas Tonka', 'Ámbar', 'Madera de Agar (Oud)', 'Benzuí', 'Mirra'],
  ARRAY['Dulce', 'Cálido Especiado', 'Vainilla', 'Praliné', 'Ámbar', 'Canela'],
  '12+ Horas (Duración Extrema)',
  'Modo Bestia / Enorme',
  true,
  false,
  18,
  4.9,
  142
),
(
  'armaf-cdnim',
  'Club De Nuit Intense Man Ltd Edition',
  'Armaf Dubai',
  'arabe',
  'hombre',
  75000.00,
  95000.00,
  ARRAY[105],
  '/images/arabic_oud.png',
  'El rey indiscutible de la perfumería árabe masculina inspirada en Creed Aventus. Apertura ahumada cítrica de piña y abedul con un secado terroso, almizclado y ultra elegante que deja una estela imborrable.',
  ARRAY['Piña', 'Limón', 'Grosella Negra', 'Manzana', 'Bergamota'],
  ARRAY['Abedul Ahumado', 'Jazmín', 'Rosa Oriental'],
  ARRAY['Almizcle Blanco', 'Ámbar Gris', 'Pachulí', 'Vainilla'],
  ARRAY['Cítrico Ahumado', 'Frutal', 'Amaderado', 'Cuero', 'Almizclado'],
  '10-12 Horas',
  'Muy Fuerte (Deja Estela)',
  true,
  false,
  24,
  4.8,
  230
),
(
  'initio-oud-for-greatness-clone',
  'Bade''e Al Oud (Oud for Glory)',
  'Lattafa Perfumes',
  'arabe',
  'unisex',
  62000.00,
  79000.00,
  ARRAY[100],
  '/images/designer_black.png',
  'Un perfume de prestigio místico. Oud For Glory destaca por su acorde de azafrán real, nuez moscada y aceite de Oud natural de alta pureza. Misterioso, nocturno y de elegancia imponente.',
  ARRAY['Azafrán', 'Nuez Moscada', 'Lavanda Real'],
  ARRAY['Madera de Oud Natural', 'Pachulí'],
  ARRAY['Oud Oscuro', 'Pachulí', 'Almizcle'],
  ARRAY['Oud', 'Especiado', 'Azafrán', 'Amaderado', 'Místico'],
  '12+ Horas',
  'Enorme',
  false,
  true,
  12,
  4.9,
  88
),
(
  'zimaya-sharaf-blend',
  'Sharaf Blend Extrait',
  'Zimaya Afnan',
  'arabe',
  'unisex',
  59000.00,
  72000.00,
  ARRAY[100],
  '/images/amber_vanilla.png',
  'Una suntuosa mezcla gourmand de coñac, licor de roble, manzana caramelizada y haba tonka con toques de sándalo oriental. Un aroma cálido y seductor para momentos inolvidables.',
  ARRAY['Nuez Moscada', 'Azafrán', 'Dátiles'],
  ARRAY['Vainilla', 'Praliné', 'Nube de Dulce'],
  ARRAY['Haba Tonka', 'Sándalo', 'Benzuí', 'Ámbar'],
  ARRAY['Gourmand', 'Licorado', 'Vainilla', 'Cálido', 'Manzana'],
  '10+ Horas',
  'Fuerte',
  true,
  true,
  15,
  4.8,
  64
),
(
  'dior-sauvage-elixir',
  'Sauvage Elixir',
  'Dior Paris',
  'disenador',
  'hombre',
  185000.00,
  210000.00,
  ARRAY[60, 100],
  '/images/royal_blue.png',
  'La concentración definitiva de la elegancia masculina. Sauvage Elixir extrae un corazón nocturno de especias embriagadoras, lavanda hecha a medida y un fondo de maderas ricas y regaliz refinado.',
  ARRAY['Nuez Moscada', 'Canela', 'Cardamomo', 'Toronja'],
  ARRAY['Lavanda de Provenza de Grasse'],
  ARRAY['Regaliz', 'Sándalo', 'Ámbar', 'Pachulí', 'Vértiver'],
  ARRAY['Cálido Especiado', 'Amaderado', 'Lavanda', 'Fresco Especiado', 'Aromático'],
  '14+ Horas (Ultra Duradero)',
  'Modo Bestia',
  true,
  false,
  9,
  5.0,
  310
),
(
  'tom-ford-tobacco-vanille',
  'Tobacco Vanille Private Blend',
  'Tom Ford',
  'nicho',
  'unisex',
  295000.00,
  340000.00,
  ARRAY[50, 100],
  '/images/designer_black.png',
  'La quintaesencia del club de caballeros inglés en una botella. Hojas de tabaco aromático, especias de oriente, haba tonka, flor de tabaco y cacao suntuoso con un toque de frutos secos.',
  ARRAY['Hojas de Tabaco', 'Especias Orientales'],
  ARRAY['Vainilla', 'Cacao', 'Haba Tonka', 'Flor de Tabaco'],
  ARRAY['Frutos Secos', 'Notas Amaderadas'],
  ARRAY['Tabaco', 'Vainilla', 'Dulce Especiado', 'Cacao', 'Cálido'],
  '12+ Horas',
  'Enorme',
  false,
  false,
  6,
  4.9,
  195
),
(
  'bleu-de-chanel-parfum',
  'Bleu de Chanel Parfum',
  'Chanel Paris',
  'disenador',
  'hombre',
  170000.00,
  195000.00,
  ARRAY[50, 100],
  '/images/royal_blue.png',
  'La expresión más intensa de Bleu de Chanel. Un perfume sofisticado que abre con frescura aromática y evoluciona hacia una firma majestuosa de sándalo de Nueva Caledonia y cedro azul.',
  ARRAY['Cáscara de Limón', 'Bergamota', 'Menta', 'Artemisa'],
  ARRAY['Lavanda', 'Piña', 'Geranio', 'Notas Verdes'],
  ARRAY['Sándalo', 'Cedro', 'Amberwood', 'Iso E Super', 'Habas Tonka'],
  ARRAY['Amaderado', 'Cítrico Elegante', 'Aromático', 'Ámbar', 'Fresco'],
  '9-11 Horas',
  'Moderada a Fuerte',
  true,
  false,
  14,
  4.8,
  278
),
(
  'jpg-lemale-elixir',
  'Le Male Elixir Parfum',
  'Jean Paul Gaultier',
  'disenador',
  'hombre',
  145000.00,
  165000.00,
  ARRAY[75, 125],
  '/images/amber_vanilla.png',
  'Una sensual ola de calor tropical y seducción dorado-metálica. Menta fresca chispeante envuelta en lavanda, miel dorada silvestre, benzui y una tonka cremosa adictiva.',
  ARRAY['Menta Fresca', 'Lavanda'],
  ARRAY['Miel Silvestre', 'Benzuí'],
  ARRAY['Vainilla', 'Haba Tonka', 'Tabaco Dorado'],
  ARRAY['Dulce Miel', 'Vainilla', 'Aromático', 'Cálido', 'Menta'],
  '12+ Horas',
  'Muy Fuerte',
  true,
  true,
  20,
  4.9,
  180
)
ON CONFLICT (id) DO UPDATE SET
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price;
